server:
  port: 8821
  servlet:
    context-path: /family-server
  undertow:
    accesslog:
      enabled: true
      dir: ${logging.path}
      pattern: '%t %a "%r" %s (%D ms)'
    worker-threads: 200
spring:
  application:
    name: family-server
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  path: /data/log/${spring.application.name}

yg:
  rest-config:
    #核心业务
    primary:
      connect-timeout: 1000
      so-timeout: 3000
    secondary:
      connect-timeout: 1000
      so-timeout: 1000
  config:

  rest-url:
#    sendMsgUrl: http://yzm.chelaile.net.cn/sms?phone={phone}&num={num}&time={time}&source=inertcity&other=inertcity
#    poiSearchUrl: http://baseservice.chelaile.net.cn/baseservice/deffered/search.action?cityId={cityId}&key={key}
#    ##百度api根据关键字查找位置
#    baiduPoiUrl: http://api.map.baidu.com/place/v2/search
#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage:  cn.keepting.family.server.dao
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper 调试神器
    refresh-mapper: false
    #数据库大写下划线转换
    capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  #    db-column-underline: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  metrics:
    #这个配置项很重要，dashborad中对应的应用名字
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
  health:
    redis:
      enabled: false
